export const SET_FORGOT_PASSWORD: 'SET_FORGOT_PASSWORD' = 'SET_FORGOT_PASSWORD';
export const SET_FORGOT_PASSWORD_REQUEST: 'SET_FORGOT_PASSWORD_REQUEST' = 'SET_FORGOT_PASSWORD_REQUEST';
export const SET_FORGOT_PASSWORD_SUCCESS: 'SET_FORGOT_PASSWORD_SUCCESS' = 'SET_FORGOT_PASSWORD_SUCCESS';
export const SET_FORGOT_PASSWORD_FAILED: 'SET_FORGOT_PASSWORD_FAILED' = 'SET_FORGOT_PASSWORD_FAILED';