export const SET_USER_UPDATE_REQUEST: 'SET_USER_UPDATE_REQUEST' = 'SET_USER_UPDATE_REQUEST';
export const SET_USER_UPDATE_SUCCESS: 'SET_USER_UPDATE_SUCCESS' = 'SET_USER_UPDATE_SUCCESS';
export const SET_USER_UPDATE_FAILED: 'SET_USER_UPDATE_FAILED' = 'SET_USER_UPDATE_FAILED';