export const APP_WS_CONNECT: 'APP_WS_CONNECT' = 'APP_WS_CONNECT';
export const APP_WS_DISCONNECT: 'APP_WS_DISCONNECT' = 'APP_WS_DISCONNECT';

export const WEBSOCKET_CONNECTING: 'WEBSOCKET_CONNECTING' = 'WEBSOCKET_CONNECTING';
export const WEBSOCKET_OPEN: 'WEBSOCKET_OPEN' = 'WEBSOCKET_OPEN';
export const WEBSOCKET_CLOSE: 'WEBSOCKET_CLOSE' = 'WEBSOCKET_CLOSE';
export const WEBSOCKET_ERROR: 'WEBSOCKET_ERROR' = 'WEBSOCKET_ERROR';
export const WEBSOCKET_MESSAGE: 'WEBSOCKET_MESSAGE' = 'WEBSOCKET_MESSAGE';
export const WEBSOCKET_SEND_MESSAGE: 'WEBSOCKET_SEND_MESSAGE' = 'WEBSOCKET_SEND_MESSAGE';


